version: '2'
services:
  db:
    image: mysql
    container_name: bacs485-univ-db
    ports:
      - "3306:3306"
    volumes:
      - ./seed:/var/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=univ_password
      - MYSQL_DATABASE=University
      - MYSQL_USER=UniversityUser
      - MYSQL_PASSWORD=UniversityPassword
